{{- if not .Values.controller.disabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app: vcluster-controller
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- if .Values.controller.labels }}
{{ toYaml .Values.controller.labels | indent 4 }}
{{- end }}
  {{- if .Values.controller.annotations }}
  annotations:
{{ toYaml .Values.controller.annotations | indent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.controller.replicas }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      {{- if (eq (int .Values.controller.replicas) 1) }}
      maxUnavailable: 0
      {{- else }}
      maxUnavailable: 1
      {{- end }}
    type: RollingUpdate
  selector:
    matchLabels:
      app: vcluster-controller
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: vcluster-controller
        release: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 10
      {{- if .Values.controller.affinity }}
      affinity:
{{ toYaml .Values.controller.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.controller.topologySpreadConstraints }}
      topologySpreadConstraints:
{{ toYaml .Values.controller.topologySpreadConstraints | indent 8 }}
      {{- end }}
      nodeSelector:
{{ toYaml .Values.controller.nodeSelector | indent 8 }}
      affinity:
{{ toYaml .Values.controller.affinity | indent 8 }}
      tolerations:
{{ toYaml .Values.controller.tolerations | indent 8 }}
      automountServiceAccountToken: false
      volumes:
        - name: certs
          secret:
            secretName: {{ .Release.Name }}-certs
      {{- if .Values.controller.volumes }}
{{ toYaml .Values.controller.volumes | indent 8 }}
      {{- end }}
      containers:
      - name: kube-controller-manager
        image: "{{ .Values.controller.image }}"
        command:
          - kube-controller-manager
          - '--authentication-kubeconfig=/run/config/pki/controller-manager.conf'
          - '--authorization-kubeconfig=/run/config/pki/controller-manager.conf'
          {{- if .Values.ipv6 }}
          - '--bind-address=::'
          {{- else }}
          - '--bind-address=0.0.0.0'
          {{- end }}
          - '--client-ca-file=/run/config/pki/ca.crt'
          - '--cluster-name=kubernetes'
          - '--cluster-signing-cert-file=/run/config/pki/ca.crt'
          - '--cluster-signing-key-file=/run/config/pki/ca.key'
          - '--controllers=*,-nodeipam,-nodelifecycle,-persistentvolume-binder,-attachdetach,-persistentvolume-expander,-cloud-node-lifecycle'
          - '--horizontal-pod-autoscaler-sync-period=60s'
          - '--kubeconfig=/run/config/pki/controller-manager.conf'
          - '--service-cluster-ip-range={{ .Values.serviceCIDR }}'
          {{- if .Values.enableHA }}
          - '--leader-elect=true'
          {{- else }}
          - '--leader-elect=false'
          {{- end }}
          - '--node-monitor-grace-period=180s'
          - '--node-monitor-period=30s'
          - '--port=0'
          - '--pvclaimbinder-sync-period=60s'
          - '--requestheader-client-ca-file=/run/config/pki/front-proxy-ca.crt'
          - '--root-ca-file=/run/config/pki/ca.crt'
          - '--service-account-private-key-file=/run/config/pki/sa.key'
          - '--use-service-account-credentials=true'
          {{- range $f := .Values.controller.extraArgs }}
          - {{ $f | quote }}
          {{- end }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10257
            scheme: HTTPS
          initialDelaySeconds: 10
          timeoutSeconds: 15
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 8
        startupProbe:
          httpGet:
            path: /healthz
            port: 10257
            scheme: HTTPS
          initialDelaySeconds: 10
          timeoutSeconds: 15
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 24
        securityContext:
{{ toYaml .Values.controller.securityContext | indent 10 }}
        env:
{{ toYaml .Values.controller.env | indent 10 }}
        volumeMounts:
          - mountPath: /run/config/pki
            name: certs
            readOnly: true
        {{- if .Values.controller.volumeMounts }}
{{ toYaml .Values.controller.volumeMounts | indent 10 }}
        {{- end }}
        resources:
{{ toYaml .Values.controller.resources | indent 10 }}
{{- end }}