{{- if not .Values.etcd.disabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-etcd-headless
  namespace: {{ .Release.Namespace }}
  labels:
    app: vcluster-etcd
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ipFamilyPolicy: SingleStack
  ipFamilies:
  {{- if .Values.ipv6 }}
  - IPv6
  {{- else }}
  - IPv4
  {{- end }}
  ports:
    - name: etcd
      port: 2379
      targetPort: 2379
      protocol: TCP
    - name: peer
      port: 2380
      targetPort: 2380
      protocol: TCP
  clusterIP: None
  selector:
    app: vcluster-etcd
    release: "{{ .Release.Name }}"
{{- end }}