{{- if and .Values.isolation.enabled .Values.isolation.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-workloads
  namespace: {{ .Values.isolation.namespace | default .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      vcluster.loft.sh/managed-by: {{ .Release.Name }}
  egress:
    # Allows outgoing connections to the vcluster control plane
    - ports:
        - port: 443
        - port: 8443
      to:
        - podSelector:
            matchLabels:
              release: {{ .Release.Name }}
    # Allows outgoing connections to DNS server
    - ports:
      - port: 53
        protocol: UDP
      - port: 53
        protocol: TCP
    # Allows outgoing connections to the internet or
    # other vcluster workloads
    - to:
        - podSelector:
            matchLabels:
              vcluster.loft.sh/managed-by: {{ .Release.Name }}
        - ipBlock:
            cidr: {{ .Values.isolation.networkPolicy.outgoingConnections.ipBlock.cidr }}
            except:
              {{- range .Values.isolation.networkPolicy.outgoingConnections.ipBlock.except }}
              - {{ . }}
              {{- end }}
  policyTypes:
    - Egress
---
# Allows all traffic between vcluster workloads unless zero trust mode is enabled
# In addition this will allow all traffic from workloads to control plane unless
# --target-namespace is configured
{{- if not .Values.isolation.networkPolicy.zeroTrust.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-ingress
  namespace: {{ .Values.isolation.namespace | default .Release.Namespace }}
spec:
  podSelector: {}
  ingress:
  - {}
  policyTypes:
  - Ingress
{{- end }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-control-plane
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      release: {{ .Release.Name }}
  egress:
    # Allows outgoing connections to all pods with
    # port 443, 8443 or 6443. This is needed for host Kubernetes
    # access
    - ports:
        - port: 443
        - port: 8443
        - port: 6443
    # Allows outgoing connections to all vcluster workloads
    # or kube system dns server
    - to:
        - podSelector: {}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: 'kube-system'
          podSelector:
            matchLabels:
              k8s-app: kube-dns
  policyTypes:
    - Egress
---
# Allows incoming connections to vcluster from outside of it
{{- if and .Values.isolation.networkPolicy.incomingConnections.vclusterAllow.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-ingress-control-plane
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: {}
  ingress:
    - from:
        - ipBlock:
            cidr: {{ .Values.isolation.networkPolicy.incomingConnections.vclusterAllow.ipBlock.cidr }}
            except:
              {{- range .Values.isolation.networkPolicy.incomingConnections.vclusterAllow.ipBlock.except }}
              - {{ . }}
              {{- end }}
      ports:
        - port: 8443
  policyTypes:
  - Ingress
{{- end }}
{{- end }}