kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: host-cluster-1
networking:
  apiServerAddress: 127.0.0.11
  apiServerPort: 6443
  disableDefaultCNI: true
  kubeProxyMode: none
  podSubnet: 10.1.0.0/16
  serviceSubnet: 10.96.0.0/12
